import React, { useRef } from "react";
import { Button, Card, Col, Container, Form, Row } from "react-bootstrap";

const SetupTwo = () => {
  return (
    <Container
      style={{ paddingLeft: "6rem", paddingRight: "6rem", paddingTop: "2rem" }}
    >
      <Row>
        <Col>
          <h3>Enable</h3>
        </Col>
      </Row>
      <Row style={{ marginTop: "1rem" }}>
        <Col>
          <Card
            style={{
              boxShadow: "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px",
              border: "none",
            }}
          >
            <Card.Body>
              <p style={{ fontSize: "15px" }}>
                To start using a token generator, please use your smartphone to
                scan the QR code below. For example, use Google Authenticator.
                Then, enter the token generated by the app.
              </p>
              <Card.Text>
                <Row>
                  <Col>QR Code here</Col>
                </Row>
                <Row>
                  <Col>
                    {" "}
                    <Form.Group className="mb-3">
                      <Form.Label>Token</Form.Label>
                      <Form.Control
                        name="token"
                        type="number"
                        min={0}
                        required
                        // ref={token}
                      />
                    </Form.Group>
                  </Col>
                </Row>
                <Row>
                  <Col style={{ textAlign: "left" }}>
                    <Button
                      as="input"
                      type="button"
                      variant="secondary"
                      value="Back"
                      style={{
                        background: "white",
                        color: "#000",
                      }}
                    />{" "}
                    <Button as="input" type="button" value="Next" />
                  </Col>
                  <Col style={{ textAlign: "right" }}>
                    <Button
                      as="input"
                      type="button"
                      variant="secondary"
                      value="Cancel"
                      style={{
                        background: "white",
                        color: "#000",
                        border: "none",
                      }}
                    />
                  </Col>
                </Row>
              </Card.Text>
            </Card.Body>
          </Card>
        </Col>
      </Row>
    </Container>
  );
};
export default SetupTwo;
